name: Test Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # зависимости
      - name: Install dependencies
        run: make setup

      # линтер
      - name: Run linter
        run: make lint

      # тесты
      - name: Run tests
        run: make test